apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-node-cache-shard-01
  namespace: cloud-node
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-cache-rwx-replica2
  resources:
    requests:
      storage: 5Ti
